### ISSUE TITLE
successful inject should delete distro in repository

### ISSUE THREAD

**Issue by XSven** [briandfoy/cpan-mini-inject#12]
A success `mcpani --inject` should delete/clean the distro in the repository because it is now in the DarkPAN mirror.

**Comment by briandfoy** [comment]
I don't know if I follow you there and I think this behavior might be surprising for some people. Maybe another switch to ask for it to be deleted. If someone was going to do that, they'd have to ensure that the file was correctly injected by comparing the destination file to the original.

**Comment by XSven** [comment]
This

> ...,they'd have to ensure that the file was correctly injected by comparing the destination file to the original.

is in the responsibility of `mcpani`: `mcpani --inject` should fail with a non-zreo exit status, if the files (destination and original) are different. If this isn't the case already today I would say it is a major deficit or even a bug.

Let me explain our use case in more detail. Maybe this even leads to a raised priority. We have a deticated **darkpan** user that based on a time schedule mirrors regularly. Other users `--add` modules to the repository. So the idea is to execute the `--inject` based on a time schedule regularly too. This makes only sense if `--inject` implies deletion.

**Comment by briandfoy** [comment]
The `inject` docs don't mention doing anything other than taking a file and adding it. It doesn't really matter what it should do, that's just what it does now. Remember, I'm not the designer or implementor of any of this.

I still don't understand your process. What is happening that makes this a problem for you? Are you calling `--inject` multiple times for each file because each periodic task injects everything in the repo into the mirror? What problems do you see in the mirror in your process?

Is this something that you could solve by deleting the file you just injected in whatever script or program handles your periodic process?

**Comment by XSven** [comment]
`--inject` isn't applied to a specific file but to all of the files in the repository.

> --inject            Add modules from repository to CPAN mirror

Yes I want to schedule `--inject` and I have tried to describe that. Why should I `--inject` the same modules again and again? Even if this works (due to an overwrite) it makes no sense to me and should be prevented. An `--inject` should be done only once per module. I am not thinking about a workaround if I see a clear deficit of tool like `mcpani`.

I am aware that you are not the designer of this module but still this issue asks for a design change whoever will implement this. For me it matters what `mcpani` should do and I don't care that today it is doing things half only.

**Comment by briandfoy** [comment]
It makes sense when you realize that this tool doesn't not inspect the state of the mirror. To ensure the files in the repo make it into the mirror, it always injects everything. Maybe you deleted the Mini CPAN, or something else deleted files. Or maybe the file in the repo has the same name but is actually different. The easiest way to be consistent is to simply inject it again to ensure that the end state you want is the actual end state.

Consider, for example, the case that you patch a module on CPAN, so your file in the repo has the same name as a file on the actual CPAN (maybe aside from version). When you update the Mini CPAN, that file might disappear because CPAN::Mini deletes it as part of `update_mirror`. This is also one of the situations where you'd want to specify the author name instead of using a default author name (#14). Someone wants to replace a file in a particular author directory. That you don't want to do that does not mean we are going to take that away.

Going back to my question, once you inject can you just delete all the files in the repo (the directory that contains the file to inject)?

    mcpani --inject && rm /path/to/repo/*
     
This goes back to my response in #13. There are many things you can do on your own without making it a feature of this module. With very specific requirements, you can modify *mcpani* to do what you want. I think that would work out better for some of the restrictions you want.

**Comment by XSven** [comment]
Now I have got it. When reading [DESCRIPTION](https://metacpan.org/pod/CPAN::Mini::Inject#DESCRIPTION) I haven't understood the attend purpose of the repository. For my use case the repository is in the way because I wanted to add a distribution directly to the mirror and not adding it to the repository and then inject it to the mirror. Is this (**add to mirror directly bypassing the repository**) a valid feature request that you would accept?

**Comment by briandfoy** [comment]
I'm mostly not going to change how CPAN::Mini::Inject works. It appears that you don't want this tool, so maybe you fork it and create your own tool to do exactly what you want.
