### ISSUE TITLE
use ~/.pause file to set the default authorid

### ISSUE THREAD

**Issue by XSven** [briandfoy/cpan-mini-inject#14]
I don't know if the [~/.pause](https://metacpan.org/dist/CPAN-Uploader/view/bin/cpan-upload#CONFIGURATION) file is a kind of standard. If yes it could be used to set a default value for the `authorid`.

**Comment by briandfoy** [comment]
That's a good idea.

**Comment by briandfoy** [comment]
I think this should be a setting in the CPAN::Mini config. Would that work for you?

**Comment by XSven** [comment]
I don't understand why `CPAN::Mini` needs the `authorid`. It should be a boolean flag `take_authorid_from_pause_file` (maybe a shorter name:-)) in `$HOME/.mcpani/config`.

**Comment by briandfoy** [comment]
We need the author id because that's how CPAN works, and Mini CPAN is a CPAN mirror.

The author name is part of the repository structure of PAUSE, so when you look in the repo you see paths like (B/BR/BRIANDFOY/Some-Module-1.23.tgz*. This splits the files into separate directories so the file count in each directory is low. Filesystem things tend to get slow when the directory contains. MiniCPAN contains tens of thousands of files (jsut checked, and got 49803), and putting all of those in one directory would make things really slow. Even within a particular author, the count can potentially be large. This sort of hashing is common in large repositories.

Aside from that, the CPAN tools expect this. Instead of inventing some new structure so that a Mini CPAN is different from the real one, we keep the original structure so the tools don't have to know which one they are dealing with. It's easier to look like a "real" mirror  than be different.

PAUSE knows the author name from the logged in user. Mini CPAN doesn't get that because there is no login. As such, we supply it.

But, we can put the default author id in the the minicpan config, instead of the a flag to look in some other file. Is there something that you are doing that has this value in a separate file?

**Comment by XSven** [comment]
I don't get it. `CPAN::Mini` does not need any specific (my) author id. Correct? If yes why should a default author id be configured in the  `CPAN::Mini` related configuration file. I am using the `CPAN::Uploader` and this uses _~/.pause_. _~/.pause_ contains my author id and I want `mcpani` (CLI of `CPAN::Mini::Inject`) to use that same author id when I haven't set `--authorid` explicitly. If possible I don't want to configure my author id again in a different configuration file.

**Comment by briandfoy** [comment]
I don't know where to start with "I don't get it". You have a very specific use case, which I also don't understand because you have explained it in dribbles. CPAN::Mini doesn't need your authorid because it gets everything it needs from the packages file. Nothing about CPAN::Mini is about you, so you don't need the authorid. I think your issue with most of this and the other issues you've raised is that you simply have not taken the time to understand how any of this actually works or what it does for you. It's really weird that you don't understand why CPAN::Mini doesn't need your authorid.

If your position is "I don't want to configure my author id again in a different configuration file", then I'll just outright reject this feature request. Not everyone will have the same workflow from you, and I'm not going to require people to have a second config file to configure part of CPAN::Mini::Inject.

One of the problems is that there's no reason to a priori think that the presence of a *.pause* file means anything for *mcpani*. CPAN::Uploader is a separate tool, and its coincidental presence shouldn't make a completely separate tool act differently unless you ask for it. The problem is that you don't seem to want to specify anything additional. There can't be a way that both of those can work at the same time. 

It's so amazingly simple to add a value to a configuration file, which would take you less than a minute, but you are asking for a lot of work to be done by someone else so you can avoid that. You haven't even offered to do that work. And, I think the change you want would make it worse for everyone. You've rejected the idea of making this feature available through the *mcpani* config.

I still don't quite understand why it's even a problem to type out `--authorid` in the command. You could make an alias, write a shell script wrapper, modify mcpani to do whatever you want, and so many other things. I have my authorid in an environment variable that I use to fill in everywhere I need it (and that I can change when I want to use another). None of those are that hard. Indeed, you'd already be done.

You could easily add

    $ grep -m 1 ^user .pause | awk '{ print "authorid " $2 }' > ~/.mcpani/config

Here's a simple command you could wrap:

    $ grep -m 1 ^user ~/.pause | awk '{ print $2 }' | xargs -I% mcpani --add --authorid % --file some-file

If your complaint is, like in some other issues (#12, #13), that this is inelegant, well, sure, that's somewhat true. But it's also reality, and the minuscule amount of work you have to do to engage in this reality is not unreasonable.

So, I don't think there's a way that I can satisfy you. As a maintainer I have to consider everyone's needs and desires, and I think you are just too far out of the envelope on those. 

That said, I am working on a patch to set the default authorid in the CPAN::Mini::Inject config file because I think that part is a worthy idea. CPAN::Mini::Inject is not going to look in a second configuration file, though. After I get the first patch done, I'll think about looking in an environment variable, so it's not looking directly in .env, but if you're environment is set up through that, you could get the authorid from the environment.
